name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Ensure gofmt
        run: test -z "$(gofmt -s -d .)"

      - name: Ensure go.mod is tidy
        run: go mod tidy && git diff --exit-code

      - name: Test
        run: go test ./...

      - name: Build snapshot
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --snapshot --skip=publish --clean
